### ISSUE TITLE
0.5.0: bats files and checkbashisms incompatibility 

### ISSUE THREAD

**Issue by jkroepke** [luizm/action-sh-checker#56]
Hi,

i'm running the action like this:

```yaml
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -x
        with:
          sh_checker_comment: true
          sh_checker_exclude: "tests/assets tests/bats"
          sh_checker_checkbashisms_enable: true
```

on repo: https://github.com/jkroepke/helm-secrets

dependabot opens a PR to bump the action, which is currently failing: https://github.com/jkroepke/helm-secrets/runs/7444254384?check_suite_focus=true
And here is an output from main branch: https://github.com/jkroepke/helm-secrets/runs/7296253846?check_suite_focus=true

sh-checker is finding 47 shell scripts instead 31. It looks like the newer shfmt include the bats files from the repository.

Now `checkbashisms` is confused, since it throws errors like `script tests/unit/view.bats does not appear to be a /bin/sh script; skipping` and the action will fail.
