### ISSUE TITLE
Invalid number: 2230 using shfmt

### ISSUE THREAD

**Issue by kenorb** [luizm/action-sh-checker#6]
Got the following error:
```
Validating shell scripts files using shfmt

Invalid number: 2230



The files above have some shellcheck issues

--- <standard input>.orig
+++ <standard input>
@@ -1,1 +1,2 @@
 
+

The files above have some formatting problems, you can use `shfmt -w` to fix them
```

Not sure why it's checking a standard input.

Build: [627458302](https://github.com/EA31337/EA-Tester/runs/627458302?check_suite_focus=true#step:3:25)

**Comment by luizm** [comment]
@kenorb 

I checked your build, and it was missing the checkout step:

```
    steps:
      - uses: actions/checkout@v1
      - name: Run sh-checker
        uses: luizm/action-sh-checker@v0.1.3
        env:
          .........
          .........
```

But there is no validation when no have a sh files, I will include it and a good message as well.
