### ISSUE TITLE
The files above have some shellcheck issues

### ISSUE THREAD

**Issue by kenorb** [luizm/action-sh-checker#8]
Build: [627796069](https://github.com/EA31337/EA-Tester/runs/627796069?check_suite_focus=true#step:4:9)

Output:

```
Validating shell scripts files using shellcheck



The files above have some shellcheck issues
```

Nothing more in raw logs.

Config file:

```
# yamllint disable rule:line-length
---
name: Lint
on:
  - pull_request
  - push
jobs:
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Shell Check
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -e SC1004,SC1083,SC1090,SC1091,SC1117,SC2004,SC2005,SC2015,SC2027,SC2032,SC2033,SC2034,SC2035,SC2046,SC2068,SC2070,SC2071,SC2086,SC2091,SC2103,SC2116,SC2124,SC2128,SC2145,SC2154,SC2155,SC2162,SC2164,SC2166,SC2181,SC2188,SC2206,SC2221,SC2222,SC2230
        with:
          sh_checker_comment: true
          sh_checker_shfmt_disable: true
```
